# Visible pages
[[pages]]
path = "Home.py"
name = "Home"
icon = "ğŸ¡"

[[pages]]
path = "pages/Account.py"
name = "Account"
icon = "ğŸ‘¤"

[[pages]]
path = "pages/Individual_Analyzer.py"
name = "Individual Analyzer"
icon = "ğŸ§ "

# Hidden pages (no icon = hidden from sidebar)
[[pages]]
path = "pages/Form.py"
name = "Form"

[[pages]]
path = "pages/DataCollector.py"
name = "DataCollector"

[[pages]]
path = "pages/Dashboard.py"
name = "Dashboard"

[[pages]]
path = "pages/Filter.py"
name = "Filter"
